//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_entities : DbContext
    {
        public DB_entities()
            : base("name=DB_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<customer_orders> customer_orders { get; set; }
        public virtual DbSet<filter> filters { get; set; }
        public virtual DbSet<filter_values> filter_values { get; set; }
        public virtual DbSet<order_status> order_status { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<pic> pics { get; set; }
        public virtual DbSet<privilege> privileges { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<product_list> product_list { get; set; }
        public virtual DbSet<product_type> product_type { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<shipping> shippings { get; set; }
        public virtual DbSet<subcategory> subcategories { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
