//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class filter
    {
        public filter()
        {
            this.filter_values = new HashSet<filter_values>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> prodtype_id { get; set; }
    
        public virtual product_type product_type { get; set; }
        public virtual ICollection<filter_values> filter_values { get; set; }
    }
}
