//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class filter_values
    {
        public filter_values()
        {
            this.products = new HashSet<product>();
        }
    
        public int id { get; set; }
        public int filter_id { get; set; }
        public string value { get; set; }
    
        public virtual filter filter { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}
