//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.customer_orders = new HashSet<customer_orders>();
            this.product_list = new HashSet<product_list>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string location { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public int status_id { get; set; }
        public float total { get; set; }
        public System.DateTime dt { get; set; }
        public int shipping_id { get; set; }
        public Nullable<int> payment_id { get; set; }
    
        public virtual ICollection<customer_orders> customer_orders { get; set; }
        public virtual order_status order_status { get; set; }
        public virtual payment payment { get; set; }
        public virtual shipping shipping { get; set; }
        public virtual ICollection<product_list> product_list { get; set; }
    }
}
