//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_type
    {
        public product_type()
        {
            this.filters = new HashSet<filter>();
            this.products = new HashSet<product>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int subcategory_id { get; set; }
    
        public virtual ICollection<filter> filters { get; set; }
        public virtual ICollection<product> products { get; set; }
        public virtual subcategory subcategory { get; set; }
    }
}
